{% set name = "pygraphblas" %}
{% set version = "5.1.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Graphegon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 01646672685707ba63fcdb65d5e16b2303bf6a762811ad4b95c5d918dc623392

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numba
    - python-suitesparse-graphblas >=5.1.3,<5.2
    - scipy
    - lazy-property
    # TODO: mmparse ssgetpy

test:
  imports:
    - pygraphblas
  commands:
    - python -c "from pygraphblas import Vector, INT64 ; v = Vector.sparse(INT64, 10) ; assert v.size == 10"

about:
  home: https://github.com/Graphegon/pygraphblas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GraphBLAS for Python
  description: |
    pygraphblas is a Python wrapper around the GraphBLAS API.
  dev_url: https://github.com/Graphegon/pygraphblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
    - michelp
