{% set name = "pygraphblas" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/michelp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e88b8eb6c2446e9a0974be78ad75447c3b3ee9b8d52f549cd52a49775e3dd6c1

build:
  skip: true  # [win or py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cffi
    - graphblas
    - pytest-runner
  run:
    - python
    - cffi
    - numba

test:
  imports:
    - pygraphblas
  commands:
    - python -c "from pygraphblas import Vector, INT64 ; v = Vector.sparse(INT64, 10) ; assert v.size == 10"

about:
  home: https://github.com/michelp/pygraphblas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GraphBLAS for Python
  description: |
    pygraphblas is a Python wrapper around the GraphBLAS API.
  dev_url: https://github.com/michelp/pygraphblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
    - michelp
