{% set name = "pygraphblas" %}
{% set version = "5.1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Graphegon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 67b9af3e2178433d2294b1095a53825eeb2adf72473cb4808ee60d4f3ad84887

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - lazy-property
    - mmparse
    - numba
    - numpy <1.21
    - python >=3.7
    - python-suitesparse-graphblas >=5.1.3,<5.2
    - scipy
    - ssgetpy

test:
  imports:
    - pygraphblas
  commands:
    - pip check
    - python -c "from pygraphblas import Vector, INT64 ; v = Vector.sparse(INT64, 10) ; assert v.size == 10"
  requires:
    - pip

about:
  home: https://github.com/Graphegon/pygraphblas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GraphBLAS for Python
  description: |
    pygraphblas is a Python wrapper around the GraphBLAS API.
  dev_url: https://github.com/Graphegon/pygraphblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
    - michelp
