{% set name = "pygraphblas" %}
{% set version = "v4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/michelp/{{ name }}/archive/{{ version }}.tar.gz
  sha256: cc7e2e494ff7cea12039892c3ccd5da40413c94b742794a1b52e29207476ece2

build:
  skip: true  # [win or py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cffi
    - graphblas
    - pytest-runner
  run:
    - python
    - cffi
    - numba
    - scipy
    - pillow
    - python-graphviz
    - contextvars
    - matplotlib

test:
  imports:
    - pygraphblas
  commands:
    - python -c "from pygraphblas import GxB_IMPLEMENTATION ; assert GxB_IMPLEMENTATION == (4,0,3)"

about:
  home: https://github.com/michelp/pygraphblas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GraphBLAS for Python
  description: |
    pygraphblas is a Python wrapper around the GraphBLAS API.
  dev_url: https://github.com/michelp/pygraphblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
    - michelp
