{% set name = "pygraphblas" %}
{% set version = "5.1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygraphblas-{{ version }}.tar.gz
  sha256: ecd763cf54394ca1d5e37474dcf36b8727ae001df3e3485180e0d94be81b858b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python
  run:
    - lazy-property
    - mmparse
    - numba
    - numpy <1.21
    - python
    - python-suitesparse-graphblas >=5.1.3,<5.2
    - scipy
    - ssgetpy

test:
  imports:
    - pygraphblas
  commands:
    - pip check
    - python -c "from pygraphblas import Vector, INT64 ; v = Vector.sparse(INT64, 10) ; assert v.size == 10"
  requires:
    - pip

about:
  home: https://github.com/Graphegon/pygraphblas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GraphBLAS for Python
  description: |
    pygraphblas is a Python wrapper around the GraphBLAS API.
  dev_url: https://github.com/Graphegon/pygraphblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
    - michelp
